name: .NET Build + Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore  --configuration Release -p:PostBuildEvent= 
    - name: Build Shared version
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x64 -c Release -f net8.0 --self-contained false DynamicForms.Example.Shared/DynamicForms.Example.Shared.csproj
    - name: Build Avalonia version
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x64 -c Release -f net8.0 --self-contained false DynamicForms.Example.Avalonia/DynamicForms.Example.Avalonia.csproj
    - name: Build WPF version
      if: ${{ github.event_name != 'pull_request' }}
      run: dotnet publish --os win --arch x64 -c Release -f net8.0-windows --self-contained false DynamicForms.Example.WPF/DynamicForms.Example.WPF.csproj
    - name: Get version number
      if: ${{ github.event_name != 'pull_request' }}
      id: version
      run: |
        $version = (Get-Item "DynamicForms.Library.Core\bin\Release\net8.0\DynamicForms.Library.Core.dll").VersionInfo.ProductVersion
        Write-Host $version
        $version = $version -replace "\+.*", ""
        Write-Output "number=$version" >> $env:GITHUB_OUTPUT
      shell: pwsh
    - name: Copy Nuget Packages
      if: ${{ github.event_name != 'pull_request' }}
      shell: pwsh
      run: |
        $outputDir = "$pwd\Output\"
        New-Item -ItemType Directory -Force -Path $outputDir
        Copy-Item -Path DynamicForms.Library.Avalonia\bin\Release\*.nupkg -Destination $outputDir
        Copy-Item -Path DynamicForms.Library.WPF\bin\Release\*.nupkg -Destination $outputDir
        Copy-Item -Path DynamicForms.Library.Core\bin\Release\*.nupkg -Destination $outputDir
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "Output/*"
        name: DynamicForms_${{ steps.version.outputs.number }}
